# GET (ALL) NOTES
GET http://localhost:3001/api/notes

###

# GET NOTE
GET http://localhost:3001/api/notes/1

###

# DELETE NOTE
DELETE http://localhost:3001/api/notes/2

###

# ADD NOTE
POST http://localhost:3001/api/notes
Content-Type: application/json; charset=UTF-8

{
  "content": "VS Code REST client is pretty good",
  "important": false
}
